import { C } from "./theme";

const DEFAULT_ILLUSTRIOUS_NEGATIVE_PROMPT = [
  "worst quality",
  "low quality",
  "blurry",
  "jpeg artifacts",
  "bad anatomy",
  "bad hands",
  "extra digits",
  "fewer digits",
  "deformed",
].join(", ");

export const AI_MODELS = [
  {
    id: "reve",
    name: "Reve",
    icon: "\u25C6",
    color: C.green,
    textEndpoint: "fal-ai/reve/text-to-image",
    imageEndpoint: "fal-ai/reve/edit",
    imageParam: "image_url",
    supportsImages: true,
    requiresPrompt: true,
    baseInput: {},
    params: [
      { key: "num_images", label: "Images", type: "slider", min: 1, max: 4, step: 1, default: 1 },
    ],
  },
  {
    id: "seedream",
    name: "SeeDream 4.5",
    icon: "\u25C7",
    color: C.cyan,
    textEndpoint: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    imageEndpoint: "fal-ai/bytedance/seedream/v4.5/edit",
    imageParam: "image_urls",
    supportsImages: true,
    requiresPrompt: true,
    baseInput: {},
    params: [
      { key: "num_images", label: "Images", type: "slider", min: 1, max: 4, step: 1, default: 1 },
      { key: "image_size", label: "Size", type: "select", options: ["auto_2K", "auto_4K", "square_hd", "square", "portrait_4_3", "landscape_4_3"], default: "auto_2K" },
      { key: "enable_safety_checker", label: "Safety", type: "bool", default: false },
    ],
  },
  {
    id: "nano-banana2",
    name: "Nano Banana 2",
    icon: "\u25CB",
    color: C.purple,
    textEndpoint: "fal-ai/nano-banana-2",
    imageEndpoint: "fal-ai/nano-banana-2/edit",
    imageParam: "image_urls",
    supportsImages: true,
    requiresPrompt: true,
    baseInput: {},
    params: [
      { key: "num_images", label: "Images", type: "slider", min: 1, max: 4, step: 1, default: 1 },
      { key: "resolution", label: "Resolution", type: "select", options: ["0.5K", "1K", "2K", "4K"], default: "1K" },
      { key: "aspect_ratio", label: "Aspect", type: "select", options: ["auto", "1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3"], default: "auto" },
    ],
  },
  {
    id: "clarity-upscaler",
    name: "Clarity Upscaler",
    icon: "\u25CE",
    color: C.orange,
    textEndpoint: null,
    imageEndpoint: "fal-ai/clarity-upscaler",
    imageParam: "image_url",
    supportsImages: true,
    requiresPrompt: false,
    baseInput: {},
    params: [
      { key: "upscale_factor", label: "Scale", type: "slider", min: 1, max: 4, step: 0.5, default: 2 },
      { key: "creativity", label: "Creativity", type: "slider", min: 0, max: 1, step: 0.05, default: 0.35 },
      { key: "resemblance", label: "Resemblance", type: "slider", min: 0, max: 1, step: 0.05, default: 0.6 },
      { key: "guidance_scale", label: "CFG", type: "slider", min: 0, max: 20, step: 0.5, default: 4 },
      { key: "num_inference_steps", label: "Steps", type: "slider", min: 4, max: 50, step: 1, default: 18 },
      { key: "enable_safety_checker", label: "Safety", type: "bool", default: false },
    ],
  },
  {
    id: "illustrious",
    name: "Illustrious XL",
    icon: "\u2736",
    color: C.pink,
    textEndpoint: "fal-ai/lora",
    imageEndpoint: "fal-ai/lora/image-to-image",
    imageParam: "image_url",
    supportsImages: true,
    requiresPrompt: true,
    baseInput: {
      model_name: "Bercraft/Illustrious-XL-v2.0-Stable-FP16-Diffusers",
      negative_prompt: DEFAULT_ILLUSTRIOUS_NEGATIVE_PROMPT,
    },
    params: [
      { key: "image_size", label: "Size", type: "select", options: ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"], default: "portrait_4_3" },
      { key: "num_inference_steps", label: "Steps", type: "slider", min: 10, max: 50, step: 1, default: 28 },
      { key: "guidance_scale", label: "CFG", type: "slider", min: 1, max: 10, step: 0.5, default: 5 },
      { key: "num_images", label: "Images", type: "slider", min: 1, max: 4, step: 1, default: 1 },
      { key: "enable_safety_checker", label: "Safety", type: "bool", default: false },
      { key: "lora_path", label: "LoRA URL", type: "text", default: "", placeholder: "https://.../lora.safetensors" },
      { key: "lora_scale", label: "LoRA", type: "slider", min: 0.1, max: 1.5, step: 0.05, default: 0.8 },
    ],
  },
];
